/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardlayoutImport } from './routes/_dashboard_layout'
import { Route as AuthlayoutImport } from './routes/_auth_layout'
import { Route as DashboardlayoutIndexImport } from './routes/_dashboard_layout/index'
import { Route as AuthlayoutRegisterImport } from './routes/_auth_layout/register'
import { Route as AuthlayoutLoginImport } from './routes/_auth_layout/login'
import { Route as DashboardlayoutProfileIndexImport } from './routes/_dashboard_layout/profile/index'
import { Route as DashboardlayoutProfileProfilelayoutImport } from './routes/_dashboard_layout/profile/_profile_layout'
import { Route as DashboardlayoutProfileProfilelayoutSendTicketImport } from './routes/_dashboard_layout/profile/_profile_layout/sendTicket'
import { Route as DashboardlayoutProfileProfilelayoutReservationsImport } from './routes/_dashboard_layout/profile/_profile_layout/reservations'
import { Route as DashboardlayoutProfileProfilelayoutNotificationsImport } from './routes/_dashboard_layout/profile/_profile_layout/notifications'
import { Route as DashboardlayoutProfileProfilelayoutHistoryImport } from './routes/_dashboard_layout/profile/_profile_layout/history'
import { Route as DashboardlayoutProfileProfilelayoutDetailsImport } from './routes/_dashboard_layout/profile/_profile_layout/details'
import { Route as DashboardlayoutProfileProfilelayoutAgreementsImport } from './routes/_dashboard_layout/profile/_profile_layout/agreements'
import { Route as DashboardlayoutProfileProfilelayoutAddParkingImport } from './routes/_dashboard_layout/profile/_profile_layout/addParking'
import { Route as DashboardlayoutProfileProfilelayoutAdminIndexImport } from './routes/_dashboard_layout/profile/_profile_layout/admin/index'
import { Route as DashboardlayoutProfileProfilelayoutAdminAdminlayoutImport } from './routes/_dashboard_layout/profile/_profile_layout/admin/_admin_layout'
import { Route as DashboardlayoutProfileProfilelayoutAdminAdminlayoutUsersImport } from './routes/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/users'
import { Route as DashboardlayoutProfileProfilelayoutAdminAdminlayoutTicketsImport } from './routes/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/tickets'
import { Route as DashboardlayoutProfileProfilelayoutAdminAdminlayoutParkingsImport } from './routes/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/parkings'

// Create Virtual Routes

const DashboardlayoutProfileImport = createFileRoute(
  '/_dashboard_layout/profile',
)()
const DashboardlayoutProfileProfilelayoutAdminImport = createFileRoute(
  '/_dashboard_layout/profile/_profile_layout/admin',
)()

// Create/Update Routes

const DashboardlayoutRoute = DashboardlayoutImport.update({
  id: '/_dashboard_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthlayoutRoute = AuthlayoutImport.update({
  id: '/_auth_layout',
  getParentRoute: () => rootRoute,
} as any)

const DashboardlayoutProfileRoute = DashboardlayoutProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardlayoutRoute,
} as any)

const DashboardlayoutIndexRoute = DashboardlayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardlayoutRoute,
} as any)

const AuthlayoutRegisterRoute = AuthlayoutRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthlayoutRoute,
} as any)

const AuthlayoutLoginRoute = AuthlayoutLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthlayoutRoute,
} as any)

const DashboardlayoutProfileIndexRoute =
  DashboardlayoutProfileIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardlayoutProfileRoute,
  } as any)

const DashboardlayoutProfileProfilelayoutRoute =
  DashboardlayoutProfileProfilelayoutImport.update({
    id: '/_profile_layout',
    getParentRoute: () => DashboardlayoutProfileRoute,
  } as any)

const DashboardlayoutProfileProfilelayoutAdminRoute =
  DashboardlayoutProfileProfilelayoutAdminImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => DashboardlayoutProfileProfilelayoutRoute,
  } as any)

const DashboardlayoutProfileProfilelayoutSendTicketRoute =
  DashboardlayoutProfileProfilelayoutSendTicketImport.update({
    id: '/sendTicket',
    path: '/sendTicket',
    getParentRoute: () => DashboardlayoutProfileProfilelayoutRoute,
  } as any)

const DashboardlayoutProfileProfilelayoutReservationsRoute =
  DashboardlayoutProfileProfilelayoutReservationsImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => DashboardlayoutProfileProfilelayoutRoute,
  } as any)

const DashboardlayoutProfileProfilelayoutNotificationsRoute =
  DashboardlayoutProfileProfilelayoutNotificationsImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardlayoutProfileProfilelayoutRoute,
  } as any)

const DashboardlayoutProfileProfilelayoutHistoryRoute =
  DashboardlayoutProfileProfilelayoutHistoryImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => DashboardlayoutProfileProfilelayoutRoute,
  } as any)

const DashboardlayoutProfileProfilelayoutDetailsRoute =
  DashboardlayoutProfileProfilelayoutDetailsImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => DashboardlayoutProfileProfilelayoutRoute,
  } as any)

const DashboardlayoutProfileProfilelayoutAgreementsRoute =
  DashboardlayoutProfileProfilelayoutAgreementsImport.update({
    id: '/agreements',
    path: '/agreements',
    getParentRoute: () => DashboardlayoutProfileProfilelayoutRoute,
  } as any)

const DashboardlayoutProfileProfilelayoutAddParkingRoute =
  DashboardlayoutProfileProfilelayoutAddParkingImport.update({
    id: '/addParking',
    path: '/addParking',
    getParentRoute: () => DashboardlayoutProfileProfilelayoutRoute,
  } as any)

const DashboardlayoutProfileProfilelayoutAdminIndexRoute =
  DashboardlayoutProfileProfilelayoutAdminIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardlayoutProfileProfilelayoutAdminRoute,
  } as any)

const DashboardlayoutProfileProfilelayoutAdminAdminlayoutRoute =
  DashboardlayoutProfileProfilelayoutAdminAdminlayoutImport.update({
    id: '/_admin_layout',
    getParentRoute: () => DashboardlayoutProfileProfilelayoutAdminRoute,
  } as any)

const DashboardlayoutProfileProfilelayoutAdminAdminlayoutUsersRoute =
  DashboardlayoutProfileProfilelayoutAdminAdminlayoutUsersImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () =>
      DashboardlayoutProfileProfilelayoutAdminAdminlayoutRoute,
  } as any)

const DashboardlayoutProfileProfilelayoutAdminAdminlayoutTicketsRoute =
  DashboardlayoutProfileProfilelayoutAdminAdminlayoutTicketsImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () =>
      DashboardlayoutProfileProfilelayoutAdminAdminlayoutRoute,
  } as any)

const DashboardlayoutProfileProfilelayoutAdminAdminlayoutParkingsRoute =
  DashboardlayoutProfileProfilelayoutAdminAdminlayoutParkingsImport.update({
    id: '/parkings',
    path: '/parkings',
    getParentRoute: () =>
      DashboardlayoutProfileProfilelayoutAdminAdminlayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth_layout': {
      id: '/_auth_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthlayoutImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard_layout': {
      id: '/_dashboard_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardlayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth_layout/login': {
      id: '/_auth_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthlayoutLoginImport
      parentRoute: typeof AuthlayoutImport
    }
    '/_auth_layout/register': {
      id: '/_auth_layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthlayoutRegisterImport
      parentRoute: typeof AuthlayoutImport
    }
    '/_dashboard_layout/': {
      id: '/_dashboard_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardlayoutIndexImport
      parentRoute: typeof DashboardlayoutImport
    }
    '/_dashboard_layout/profile': {
      id: '/_dashboard_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardlayoutProfileImport
      parentRoute: typeof DashboardlayoutImport
    }
    '/_dashboard_layout/profile/_profile_layout': {
      id: '/_dashboard_layout/profile/_profile_layout'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardlayoutProfileProfilelayoutImport
      parentRoute: typeof DashboardlayoutProfileRoute
    }
    '/_dashboard_layout/profile/': {
      id: '/_dashboard_layout/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof DashboardlayoutProfileIndexImport
      parentRoute: typeof DashboardlayoutProfileImport
    }
    '/_dashboard_layout/profile/_profile_layout/addParking': {
      id: '/_dashboard_layout/profile/_profile_layout/addParking'
      path: '/addParking'
      fullPath: '/profile/addParking'
      preLoaderRoute: typeof DashboardlayoutProfileProfilelayoutAddParkingImport
      parentRoute: typeof DashboardlayoutProfileProfilelayoutImport
    }
    '/_dashboard_layout/profile/_profile_layout/agreements': {
      id: '/_dashboard_layout/profile/_profile_layout/agreements'
      path: '/agreements'
      fullPath: '/profile/agreements'
      preLoaderRoute: typeof DashboardlayoutProfileProfilelayoutAgreementsImport
      parentRoute: typeof DashboardlayoutProfileProfilelayoutImport
    }
    '/_dashboard_layout/profile/_profile_layout/details': {
      id: '/_dashboard_layout/profile/_profile_layout/details'
      path: '/details'
      fullPath: '/profile/details'
      preLoaderRoute: typeof DashboardlayoutProfileProfilelayoutDetailsImport
      parentRoute: typeof DashboardlayoutProfileProfilelayoutImport
    }
    '/_dashboard_layout/profile/_profile_layout/history': {
      id: '/_dashboard_layout/profile/_profile_layout/history'
      path: '/history'
      fullPath: '/profile/history'
      preLoaderRoute: typeof DashboardlayoutProfileProfilelayoutHistoryImport
      parentRoute: typeof DashboardlayoutProfileProfilelayoutImport
    }
    '/_dashboard_layout/profile/_profile_layout/notifications': {
      id: '/_dashboard_layout/profile/_profile_layout/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof DashboardlayoutProfileProfilelayoutNotificationsImport
      parentRoute: typeof DashboardlayoutProfileProfilelayoutImport
    }
    '/_dashboard_layout/profile/_profile_layout/reservations': {
      id: '/_dashboard_layout/profile/_profile_layout/reservations'
      path: '/reservations'
      fullPath: '/profile/reservations'
      preLoaderRoute: typeof DashboardlayoutProfileProfilelayoutReservationsImport
      parentRoute: typeof DashboardlayoutProfileProfilelayoutImport
    }
    '/_dashboard_layout/profile/_profile_layout/sendTicket': {
      id: '/_dashboard_layout/profile/_profile_layout/sendTicket'
      path: '/sendTicket'
      fullPath: '/profile/sendTicket'
      preLoaderRoute: typeof DashboardlayoutProfileProfilelayoutSendTicketImport
      parentRoute: typeof DashboardlayoutProfileProfilelayoutImport
    }
    '/_dashboard_layout/profile/_profile_layout/admin': {
      id: '/_dashboard_layout/profile/_profile_layout/admin'
      path: '/admin'
      fullPath: '/profile/admin'
      preLoaderRoute: typeof DashboardlayoutProfileProfilelayoutAdminImport
      parentRoute: typeof DashboardlayoutProfileProfilelayoutImport
    }
    '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout': {
      id: '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout'
      path: '/admin'
      fullPath: '/profile/admin'
      preLoaderRoute: typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutImport
      parentRoute: typeof DashboardlayoutProfileProfilelayoutAdminRoute
    }
    '/_dashboard_layout/profile/_profile_layout/admin/': {
      id: '/_dashboard_layout/profile/_profile_layout/admin/'
      path: '/'
      fullPath: '/profile/admin/'
      preLoaderRoute: typeof DashboardlayoutProfileProfilelayoutAdminIndexImport
      parentRoute: typeof DashboardlayoutProfileProfilelayoutAdminImport
    }
    '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/parkings': {
      id: '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/parkings'
      path: '/parkings'
      fullPath: '/profile/admin/parkings'
      preLoaderRoute: typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutParkingsImport
      parentRoute: typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutImport
    }
    '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/tickets': {
      id: '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/tickets'
      path: '/tickets'
      fullPath: '/profile/admin/tickets'
      preLoaderRoute: typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutTicketsImport
      parentRoute: typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutImport
    }
    '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/users': {
      id: '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/users'
      path: '/users'
      fullPath: '/profile/admin/users'
      preLoaderRoute: typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutUsersImport
      parentRoute: typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutImport
    }
  }
}

// Create and export the route tree

interface AuthlayoutRouteChildren {
  AuthlayoutLoginRoute: typeof AuthlayoutLoginRoute
  AuthlayoutRegisterRoute: typeof AuthlayoutRegisterRoute
}

const AuthlayoutRouteChildren: AuthlayoutRouteChildren = {
  AuthlayoutLoginRoute: AuthlayoutLoginRoute,
  AuthlayoutRegisterRoute: AuthlayoutRegisterRoute,
}

const AuthlayoutRouteWithChildren = AuthlayoutRoute._addFileChildren(
  AuthlayoutRouteChildren,
)

interface DashboardlayoutProfileProfilelayoutAdminAdminlayoutRouteChildren {
  DashboardlayoutProfileProfilelayoutAdminAdminlayoutParkingsRoute: typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutParkingsRoute
  DashboardlayoutProfileProfilelayoutAdminAdminlayoutTicketsRoute: typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutTicketsRoute
  DashboardlayoutProfileProfilelayoutAdminAdminlayoutUsersRoute: typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutUsersRoute
}

const DashboardlayoutProfileProfilelayoutAdminAdminlayoutRouteChildren: DashboardlayoutProfileProfilelayoutAdminAdminlayoutRouteChildren =
  {
    DashboardlayoutProfileProfilelayoutAdminAdminlayoutParkingsRoute:
      DashboardlayoutProfileProfilelayoutAdminAdminlayoutParkingsRoute,
    DashboardlayoutProfileProfilelayoutAdminAdminlayoutTicketsRoute:
      DashboardlayoutProfileProfilelayoutAdminAdminlayoutTicketsRoute,
    DashboardlayoutProfileProfilelayoutAdminAdminlayoutUsersRoute:
      DashboardlayoutProfileProfilelayoutAdminAdminlayoutUsersRoute,
  }

const DashboardlayoutProfileProfilelayoutAdminAdminlayoutRouteWithChildren =
  DashboardlayoutProfileProfilelayoutAdminAdminlayoutRoute._addFileChildren(
    DashboardlayoutProfileProfilelayoutAdminAdminlayoutRouteChildren,
  )

interface DashboardlayoutProfileProfilelayoutAdminRouteChildren {
  DashboardlayoutProfileProfilelayoutAdminAdminlayoutRoute: typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutRouteWithChildren
  DashboardlayoutProfileProfilelayoutAdminIndexRoute: typeof DashboardlayoutProfileProfilelayoutAdminIndexRoute
}

const DashboardlayoutProfileProfilelayoutAdminRouteChildren: DashboardlayoutProfileProfilelayoutAdminRouteChildren =
  {
    DashboardlayoutProfileProfilelayoutAdminAdminlayoutRoute:
      DashboardlayoutProfileProfilelayoutAdminAdminlayoutRouteWithChildren,
    DashboardlayoutProfileProfilelayoutAdminIndexRoute:
      DashboardlayoutProfileProfilelayoutAdminIndexRoute,
  }

const DashboardlayoutProfileProfilelayoutAdminRouteWithChildren =
  DashboardlayoutProfileProfilelayoutAdminRoute._addFileChildren(
    DashboardlayoutProfileProfilelayoutAdminRouteChildren,
  )

interface DashboardlayoutProfileProfilelayoutRouteChildren {
  DashboardlayoutProfileProfilelayoutAddParkingRoute: typeof DashboardlayoutProfileProfilelayoutAddParkingRoute
  DashboardlayoutProfileProfilelayoutAgreementsRoute: typeof DashboardlayoutProfileProfilelayoutAgreementsRoute
  DashboardlayoutProfileProfilelayoutDetailsRoute: typeof DashboardlayoutProfileProfilelayoutDetailsRoute
  DashboardlayoutProfileProfilelayoutHistoryRoute: typeof DashboardlayoutProfileProfilelayoutHistoryRoute
  DashboardlayoutProfileProfilelayoutNotificationsRoute: typeof DashboardlayoutProfileProfilelayoutNotificationsRoute
  DashboardlayoutProfileProfilelayoutReservationsRoute: typeof DashboardlayoutProfileProfilelayoutReservationsRoute
  DashboardlayoutProfileProfilelayoutSendTicketRoute: typeof DashboardlayoutProfileProfilelayoutSendTicketRoute
  DashboardlayoutProfileProfilelayoutAdminRoute: typeof DashboardlayoutProfileProfilelayoutAdminRouteWithChildren
}

const DashboardlayoutProfileProfilelayoutRouteChildren: DashboardlayoutProfileProfilelayoutRouteChildren =
  {
    DashboardlayoutProfileProfilelayoutAddParkingRoute:
      DashboardlayoutProfileProfilelayoutAddParkingRoute,
    DashboardlayoutProfileProfilelayoutAgreementsRoute:
      DashboardlayoutProfileProfilelayoutAgreementsRoute,
    DashboardlayoutProfileProfilelayoutDetailsRoute:
      DashboardlayoutProfileProfilelayoutDetailsRoute,
    DashboardlayoutProfileProfilelayoutHistoryRoute:
      DashboardlayoutProfileProfilelayoutHistoryRoute,
    DashboardlayoutProfileProfilelayoutNotificationsRoute:
      DashboardlayoutProfileProfilelayoutNotificationsRoute,
    DashboardlayoutProfileProfilelayoutReservationsRoute:
      DashboardlayoutProfileProfilelayoutReservationsRoute,
    DashboardlayoutProfileProfilelayoutSendTicketRoute:
      DashboardlayoutProfileProfilelayoutSendTicketRoute,
    DashboardlayoutProfileProfilelayoutAdminRoute:
      DashboardlayoutProfileProfilelayoutAdminRouteWithChildren,
  }

const DashboardlayoutProfileProfilelayoutRouteWithChildren =
  DashboardlayoutProfileProfilelayoutRoute._addFileChildren(
    DashboardlayoutProfileProfilelayoutRouteChildren,
  )

interface DashboardlayoutProfileRouteChildren {
  DashboardlayoutProfileProfilelayoutRoute: typeof DashboardlayoutProfileProfilelayoutRouteWithChildren
  DashboardlayoutProfileIndexRoute: typeof DashboardlayoutProfileIndexRoute
}

const DashboardlayoutProfileRouteChildren: DashboardlayoutProfileRouteChildren =
  {
    DashboardlayoutProfileProfilelayoutRoute:
      DashboardlayoutProfileProfilelayoutRouteWithChildren,
    DashboardlayoutProfileIndexRoute: DashboardlayoutProfileIndexRoute,
  }

const DashboardlayoutProfileRouteWithChildren =
  DashboardlayoutProfileRoute._addFileChildren(
    DashboardlayoutProfileRouteChildren,
  )

interface DashboardlayoutRouteChildren {
  DashboardlayoutIndexRoute: typeof DashboardlayoutIndexRoute
  DashboardlayoutProfileRoute: typeof DashboardlayoutProfileRouteWithChildren
}

const DashboardlayoutRouteChildren: DashboardlayoutRouteChildren = {
  DashboardlayoutIndexRoute: DashboardlayoutIndexRoute,
  DashboardlayoutProfileRoute: DashboardlayoutProfileRouteWithChildren,
}

const DashboardlayoutRouteWithChildren = DashboardlayoutRoute._addFileChildren(
  DashboardlayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof DashboardlayoutRouteWithChildren
  '/login': typeof AuthlayoutLoginRoute
  '/register': typeof AuthlayoutRegisterRoute
  '/': typeof DashboardlayoutIndexRoute
  '/profile': typeof DashboardlayoutProfileProfilelayoutRouteWithChildren
  '/profile/': typeof DashboardlayoutProfileIndexRoute
  '/profile/addParking': typeof DashboardlayoutProfileProfilelayoutAddParkingRoute
  '/profile/agreements': typeof DashboardlayoutProfileProfilelayoutAgreementsRoute
  '/profile/details': typeof DashboardlayoutProfileProfilelayoutDetailsRoute
  '/profile/history': typeof DashboardlayoutProfileProfilelayoutHistoryRoute
  '/profile/notifications': typeof DashboardlayoutProfileProfilelayoutNotificationsRoute
  '/profile/reservations': typeof DashboardlayoutProfileProfilelayoutReservationsRoute
  '/profile/sendTicket': typeof DashboardlayoutProfileProfilelayoutSendTicketRoute
  '/profile/admin': typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutRouteWithChildren
  '/profile/admin/': typeof DashboardlayoutProfileProfilelayoutAdminIndexRoute
  '/profile/admin/parkings': typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutParkingsRoute
  '/profile/admin/tickets': typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutTicketsRoute
  '/profile/admin/users': typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutUsersRoute
}

export interface FileRoutesByTo {
  '': typeof AuthlayoutRouteWithChildren
  '/login': typeof AuthlayoutLoginRoute
  '/register': typeof AuthlayoutRegisterRoute
  '/': typeof DashboardlayoutIndexRoute
  '/profile': typeof DashboardlayoutProfileIndexRoute
  '/profile/addParking': typeof DashboardlayoutProfileProfilelayoutAddParkingRoute
  '/profile/agreements': typeof DashboardlayoutProfileProfilelayoutAgreementsRoute
  '/profile/details': typeof DashboardlayoutProfileProfilelayoutDetailsRoute
  '/profile/history': typeof DashboardlayoutProfileProfilelayoutHistoryRoute
  '/profile/notifications': typeof DashboardlayoutProfileProfilelayoutNotificationsRoute
  '/profile/reservations': typeof DashboardlayoutProfileProfilelayoutReservationsRoute
  '/profile/sendTicket': typeof DashboardlayoutProfileProfilelayoutSendTicketRoute
  '/profile/admin': typeof DashboardlayoutProfileProfilelayoutAdminIndexRoute
  '/profile/admin/parkings': typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutParkingsRoute
  '/profile/admin/tickets': typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutTicketsRoute
  '/profile/admin/users': typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutUsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth_layout': typeof AuthlayoutRouteWithChildren
  '/_dashboard_layout': typeof DashboardlayoutRouteWithChildren
  '/_auth_layout/login': typeof AuthlayoutLoginRoute
  '/_auth_layout/register': typeof AuthlayoutRegisterRoute
  '/_dashboard_layout/': typeof DashboardlayoutIndexRoute
  '/_dashboard_layout/profile': typeof DashboardlayoutProfileRouteWithChildren
  '/_dashboard_layout/profile/_profile_layout': typeof DashboardlayoutProfileProfilelayoutRouteWithChildren
  '/_dashboard_layout/profile/': typeof DashboardlayoutProfileIndexRoute
  '/_dashboard_layout/profile/_profile_layout/addParking': typeof DashboardlayoutProfileProfilelayoutAddParkingRoute
  '/_dashboard_layout/profile/_profile_layout/agreements': typeof DashboardlayoutProfileProfilelayoutAgreementsRoute
  '/_dashboard_layout/profile/_profile_layout/details': typeof DashboardlayoutProfileProfilelayoutDetailsRoute
  '/_dashboard_layout/profile/_profile_layout/history': typeof DashboardlayoutProfileProfilelayoutHistoryRoute
  '/_dashboard_layout/profile/_profile_layout/notifications': typeof DashboardlayoutProfileProfilelayoutNotificationsRoute
  '/_dashboard_layout/profile/_profile_layout/reservations': typeof DashboardlayoutProfileProfilelayoutReservationsRoute
  '/_dashboard_layout/profile/_profile_layout/sendTicket': typeof DashboardlayoutProfileProfilelayoutSendTicketRoute
  '/_dashboard_layout/profile/_profile_layout/admin': typeof DashboardlayoutProfileProfilelayoutAdminRouteWithChildren
  '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout': typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutRouteWithChildren
  '/_dashboard_layout/profile/_profile_layout/admin/': typeof DashboardlayoutProfileProfilelayoutAdminIndexRoute
  '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/parkings': typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutParkingsRoute
  '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/tickets': typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutTicketsRoute
  '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/users': typeof DashboardlayoutProfileProfilelayoutAdminAdminlayoutUsersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/register'
    | '/'
    | '/profile'
    | '/profile/'
    | '/profile/addParking'
    | '/profile/agreements'
    | '/profile/details'
    | '/profile/history'
    | '/profile/notifications'
    | '/profile/reservations'
    | '/profile/sendTicket'
    | '/profile/admin'
    | '/profile/admin/'
    | '/profile/admin/parkings'
    | '/profile/admin/tickets'
    | '/profile/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/register'
    | '/'
    | '/profile'
    | '/profile/addParking'
    | '/profile/agreements'
    | '/profile/details'
    | '/profile/history'
    | '/profile/notifications'
    | '/profile/reservations'
    | '/profile/sendTicket'
    | '/profile/admin'
    | '/profile/admin/parkings'
    | '/profile/admin/tickets'
    | '/profile/admin/users'
  id:
    | '__root__'
    | '/_auth_layout'
    | '/_dashboard_layout'
    | '/_auth_layout/login'
    | '/_auth_layout/register'
    | '/_dashboard_layout/'
    | '/_dashboard_layout/profile'
    | '/_dashboard_layout/profile/_profile_layout'
    | '/_dashboard_layout/profile/'
    | '/_dashboard_layout/profile/_profile_layout/addParking'
    | '/_dashboard_layout/profile/_profile_layout/agreements'
    | '/_dashboard_layout/profile/_profile_layout/details'
    | '/_dashboard_layout/profile/_profile_layout/history'
    | '/_dashboard_layout/profile/_profile_layout/notifications'
    | '/_dashboard_layout/profile/_profile_layout/reservations'
    | '/_dashboard_layout/profile/_profile_layout/sendTicket'
    | '/_dashboard_layout/profile/_profile_layout/admin'
    | '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout'
    | '/_dashboard_layout/profile/_profile_layout/admin/'
    | '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/parkings'
    | '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/tickets'
    | '/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthlayoutRoute: typeof AuthlayoutRouteWithChildren
  DashboardlayoutRoute: typeof DashboardlayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthlayoutRoute: AuthlayoutRouteWithChildren,
  DashboardlayoutRoute: DashboardlayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth_layout",
        "/_dashboard_layout"
      ]
    },
    "/_auth_layout": {
      "filePath": "_auth_layout.tsx",
      "children": [
        "/_auth_layout/login",
        "/_auth_layout/register"
      ]
    },
    "/_dashboard_layout": {
      "filePath": "_dashboard_layout.tsx",
      "children": [
        "/_dashboard_layout/",
        "/_dashboard_layout/profile"
      ]
    },
    "/_auth_layout/login": {
      "filePath": "_auth_layout/login.tsx",
      "parent": "/_auth_layout"
    },
    "/_auth_layout/register": {
      "filePath": "_auth_layout/register.tsx",
      "parent": "/_auth_layout"
    },
    "/_dashboard_layout/": {
      "filePath": "_dashboard_layout/index.tsx",
      "parent": "/_dashboard_layout"
    },
    "/_dashboard_layout/profile": {
      "filePath": "_dashboard_layout/profile",
      "parent": "/_dashboard_layout",
      "children": [
        "/_dashboard_layout/profile/_profile_layout",
        "/_dashboard_layout/profile/"
      ]
    },
    "/_dashboard_layout/profile/_profile_layout": {
      "filePath": "_dashboard_layout/profile/_profile_layout.tsx",
      "parent": "/_dashboard_layout/profile",
      "children": [
        "/_dashboard_layout/profile/_profile_layout/addParking",
        "/_dashboard_layout/profile/_profile_layout/agreements",
        "/_dashboard_layout/profile/_profile_layout/details",
        "/_dashboard_layout/profile/_profile_layout/history",
        "/_dashboard_layout/profile/_profile_layout/notifications",
        "/_dashboard_layout/profile/_profile_layout/reservations",
        "/_dashboard_layout/profile/_profile_layout/sendTicket",
        "/_dashboard_layout/profile/_profile_layout/admin"
      ]
    },
    "/_dashboard_layout/profile/": {
      "filePath": "_dashboard_layout/profile/index.tsx",
      "parent": "/_dashboard_layout/profile"
    },
    "/_dashboard_layout/profile/_profile_layout/addParking": {
      "filePath": "_dashboard_layout/profile/_profile_layout/addParking.tsx",
      "parent": "/_dashboard_layout/profile/_profile_layout"
    },
    "/_dashboard_layout/profile/_profile_layout/agreements": {
      "filePath": "_dashboard_layout/profile/_profile_layout/agreements.tsx",
      "parent": "/_dashboard_layout/profile/_profile_layout"
    },
    "/_dashboard_layout/profile/_profile_layout/details": {
      "filePath": "_dashboard_layout/profile/_profile_layout/details.tsx",
      "parent": "/_dashboard_layout/profile/_profile_layout"
    },
    "/_dashboard_layout/profile/_profile_layout/history": {
      "filePath": "_dashboard_layout/profile/_profile_layout/history.tsx",
      "parent": "/_dashboard_layout/profile/_profile_layout"
    },
    "/_dashboard_layout/profile/_profile_layout/notifications": {
      "filePath": "_dashboard_layout/profile/_profile_layout/notifications.tsx",
      "parent": "/_dashboard_layout/profile/_profile_layout"
    },
    "/_dashboard_layout/profile/_profile_layout/reservations": {
      "filePath": "_dashboard_layout/profile/_profile_layout/reservations.tsx",
      "parent": "/_dashboard_layout/profile/_profile_layout"
    },
    "/_dashboard_layout/profile/_profile_layout/sendTicket": {
      "filePath": "_dashboard_layout/profile/_profile_layout/sendTicket.tsx",
      "parent": "/_dashboard_layout/profile/_profile_layout"
    },
    "/_dashboard_layout/profile/_profile_layout/admin": {
      "filePath": "_dashboard_layout/profile/_profile_layout/admin",
      "parent": "/_dashboard_layout/profile/_profile_layout",
      "children": [
        "/_dashboard_layout/profile/_profile_layout/admin/_admin_layout",
        "/_dashboard_layout/profile/_profile_layout/admin/"
      ]
    },
    "/_dashboard_layout/profile/_profile_layout/admin/_admin_layout": {
      "filePath": "_dashboard_layout/profile/_profile_layout/admin/_admin_layout.tsx",
      "parent": "/_dashboard_layout/profile/_profile_layout/admin",
      "children": [
        "/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/parkings",
        "/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/tickets",
        "/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/users"
      ]
    },
    "/_dashboard_layout/profile/_profile_layout/admin/": {
      "filePath": "_dashboard_layout/profile/_profile_layout/admin/index.tsx",
      "parent": "/_dashboard_layout/profile/_profile_layout/admin"
    },
    "/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/parkings": {
      "filePath": "_dashboard_layout/profile/_profile_layout/admin/_admin_layout/parkings.tsx",
      "parent": "/_dashboard_layout/profile/_profile_layout/admin/_admin_layout"
    },
    "/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/tickets": {
      "filePath": "_dashboard_layout/profile/_profile_layout/admin/_admin_layout/tickets.tsx",
      "parent": "/_dashboard_layout/profile/_profile_layout/admin/_admin_layout"
    },
    "/_dashboard_layout/profile/_profile_layout/admin/_admin_layout/users": {
      "filePath": "_dashboard_layout/profile/_profile_layout/admin/_admin_layout/users.tsx",
      "parent": "/_dashboard_layout/profile/_profile_layout/admin/_admin_layout"
    }
  }
}
ROUTE_MANIFEST_END */
